### PR TITLE
Made Jasper, done automatically ping OP | Added /resolved command

### PR DESCRIPTION
**Pull request by Proman4713**
You can check the discord chat for more info ☺️

### CODE REVIEW

**Comment by JayyDoesDev** [comment]
Command options need to use 
`ApplicationCommandOptionType‘ for better understandability. Also should be imported from `@antibot/interactions.
`.length` needs to be used instead of `.size` (undefined).
`Snowflake` should come from `@antibot/interactions`.

**Comment by Proman4713** [comment]
alright

**Comment by Proman4713** [comment]
> Command options need to use `ApplicationCommandOptionType‘ for better understandability. Also should be imported from `@antibot/interactions. `.length` needs to be used instead of `.size` (undefined). `Snowflake` should come from `@antibot/interactions`.

why would i specifically need to use Snowflake?

**Comment by JayyDoesDev** [comment]
> > Command options need to use `ApplicationCommandOptionType‘ for better understandability. Also should be imported from `@antibot/interactions. `.length` needs to be used instead of `.size` (undefined). `Snowflake` should come from `@antibot/interactions`.
> 
> 
> 
> why would i specifically need to use Snowflake?

Snowflakes are what you call ids for the Discord api. It's just better to use `Snowflake` via referencing than using `string`.

**Pull request merged**
